version: '3'
services:
  mariadb:
    image: mariadb:10.3-focal
    command: --default-authentication-plugin=mysql_native_password
    container_name: od2-hive-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hive
      MYSQL_ROOT_PASSWORD: password
    ports:
    - "127.0.69.69:3306:3306"
