// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package types

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskStatus int32

const (
	TaskStatus_SUCCESS        TaskStatus = 0
	TaskStatus_TIMEOUT        TaskStatus = 1
	TaskStatus_CLIENT_FAILURE TaskStatus = 2
)

var TaskStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "TIMEOUT",
	2: "CLIENT_FAILURE",
}

var TaskStatus_value = map[string]int32{
	"SUCCESS":        0,
	"TIMEOUT":        1,
	"CLIENT_FAILURE": 2,
}

func (x TaskStatus) String() string {
	return proto.EnumName(TaskStatus_name, int32(x))
}

func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

type ItemLocator struct {
	Collection           int64    `protobuf:"varint,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemLocator) Reset()         { *m = ItemLocator{} }
func (m *ItemLocator) String() string { return proto.CompactTextString(m) }
func (*ItemLocator) ProtoMessage()    {}
func (*ItemLocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *ItemLocator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemLocator.Unmarshal(m, b)
}
func (m *ItemLocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemLocator.Marshal(b, m, deterministic)
}
func (m *ItemLocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemLocator.Merge(m, src)
}
func (m *ItemLocator) XXX_Size() int {
	return xxx_messageInfo_ItemLocator.Size(m)
}
func (m *ItemLocator) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemLocator.DiscardUnknown(m)
}

var xxx_messageInfo_ItemLocator proto.InternalMessageInfo

func (m *ItemLocator) GetCollection() int64 {
	if m != nil {
		return m.Collection
	}
	return 0
}

func (m *ItemLocator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ItemPointer struct {
	Dst                  *ItemLocator         `protobuf:"bytes,1,opt,name=dst,proto3" json:"dst,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ItemPointer) Reset()         { *m = ItemPointer{} }
func (m *ItemPointer) String() string { return proto.CompactTextString(m) }
func (*ItemPointer) ProtoMessage()    {}
func (*ItemPointer) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *ItemPointer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemPointer.Unmarshal(m, b)
}
func (m *ItemPointer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemPointer.Marshal(b, m, deterministic)
}
func (m *ItemPointer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemPointer.Merge(m, src)
}
func (m *ItemPointer) XXX_Size() int {
	return xxx_messageInfo_ItemPointer.Size(m)
}
func (m *ItemPointer) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemPointer.DiscardUnknown(m)
}

var xxx_messageInfo_ItemPointer proto.InternalMessageInfo

func (m *ItemPointer) GetDst() *ItemLocator {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *ItemPointer) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type TaskResult struct {
	Item                 *ItemLocator         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	TaskId               int64                `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Pipeline             int64                `protobuf:"varint,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Status               TaskStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=od2_network.hive.TaskStatus" json:"status,omitempty"`
	FinishTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskResult) Reset()         { *m = TaskResult{} }
func (m *TaskResult) String() string { return proto.CompactTextString(m) }
func (*TaskResult) ProtoMessage()    {}
func (*TaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2}
}

func (m *TaskResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResult.Unmarshal(m, b)
}
func (m *TaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResult.Marshal(b, m, deterministic)
}
func (m *TaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResult.Merge(m, src)
}
func (m *TaskResult) XXX_Size() int {
	return xxx_messageInfo_TaskResult.Size(m)
}
func (m *TaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResult proto.InternalMessageInfo

func (m *TaskResult) GetItem() *ItemLocator {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *TaskResult) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *TaskResult) GetPipeline() int64 {
	if m != nil {
		return m.Pipeline
	}
	return 0
}

func (m *TaskResult) GetStatus() TaskStatus {
	if m != nil {
		return m.Status
	}
	return TaskStatus_SUCCESS
}

func (m *TaskResult) GetFinishTime() *timestamp.Timestamp {
	if m != nil {
		return m.FinishTime
	}
	return nil
}

func (m *TaskResult) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type GetTasksRequest struct {
	NumTasks             int32    `protobuf:"varint,1,opt,name=num_tasks,json=numTasks,proto3" json:"num_tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksRequest) Reset()         { *m = GetTasksRequest{} }
func (m *GetTasksRequest) String() string { return proto.CompactTextString(m) }
func (*GetTasksRequest) ProtoMessage()    {}
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{3}
}

func (m *GetTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksRequest.Unmarshal(m, b)
}
func (m *GetTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksRequest.Marshal(b, m, deterministic)
}
func (m *GetTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksRequest.Merge(m, src)
}
func (m *GetTasksRequest) XXX_Size() int {
	return xxx_messageInfo_GetTasksRequest.Size(m)
}
func (m *GetTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksRequest proto.InternalMessageInfo

func (m *GetTasksRequest) GetNumTasks() int32 {
	if m != nil {
		return m.NumTasks
	}
	return 0
}

type GetTasksResponse struct {
	Locators             []*ItemLocator `protobuf:"bytes,1,rep,name=locators,proto3" json:"locators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTasksResponse) Reset()         { *m = GetTasksResponse{} }
func (m *GetTasksResponse) String() string { return proto.CompactTextString(m) }
func (*GetTasksResponse) ProtoMessage()    {}
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{4}
}

func (m *GetTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksResponse.Unmarshal(m, b)
}
func (m *GetTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksResponse.Marshal(b, m, deterministic)
}
func (m *GetTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksResponse.Merge(m, src)
}
func (m *GetTasksResponse) XXX_Size() int {
	return xxx_messageInfo_GetTasksResponse.Size(m)
}
func (m *GetTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksResponse proto.InternalMessageInfo

func (m *GetTasksResponse) GetLocators() []*ItemLocator {
	if m != nil {
		return m.Locators
	}
	return nil
}

func init() {
	proto.RegisterEnum("od2_network.hive.TaskStatus", TaskStatus_name, TaskStatus_value)
	proto.RegisterType((*ItemLocator)(nil), "od2_network.hive.ItemLocator")
	proto.RegisterType((*ItemPointer)(nil), "od2_network.hive.ItemPointer")
	proto.RegisterType((*TaskResult)(nil), "od2_network.hive.TaskResult")
	proto.RegisterType((*GetTasksRequest)(nil), "od2_network.hive.GetTasksRequest")
	proto.RegisterType((*GetTasksResponse)(nil), "od2_network.hive.GetTasksResponse")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x5f, 0x8f, 0x93, 0x40,
	0x14, 0xc5, 0x17, 0xd8, 0x76, 0xe9, 0xc5, 0x54, 0x32, 0x2f, 0x22, 0xba, 0xbb, 0x95, 0xa7, 0xc6,
	0x07, 0x88, 0xa8, 0x89, 0x7f, 0xe2, 0x83, 0xd6, 0x6a, 0x48, 0xba, 0x6a, 0x06, 0xfa, 0x62, 0x4c,
	0x08, 0x5b, 0x66, 0xbb, 0x93, 0x02, 0x83, 0xcc, 0xe0, 0x9f, 0x2f, 0xe3, 0x67, 0x35, 0x33, 0xb4,
	0xdd, 0x4d, 0x9b, 0x58, 0x1f, 0x67, 0xee, 0xef, 0xcc, 0x3d, 0xe7, 0x0c, 0xdc, 0x29, 0x59, 0x4e,
	0x0a, 0xee, 0xd7, 0x0d, 0x13, 0x0c, 0xd9, 0x2c, 0x0f, 0xd3, 0x8a, 0x88, 0x9f, 0xac, 0x59, 0xf9,
	0xd7, 0xf4, 0x07, 0x71, 0xcf, 0x96, 0x8c, 0x2d, 0x0b, 0x12, 0xa8, 0xf9, 0x65, 0x7b, 0x15, 0xe4,
	0x6d, 0x93, 0x09, 0xca, 0xaa, 0x4e, 0xe1, 0x9e, 0xef, 0xce, 0x05, 0x2d, 0x09, 0x17, 0x59, 0x59,
	0x77, 0x80, 0xf7, 0x06, 0xac, 0x48, 0x90, 0x72, 0xc6, 0x16, 0x99, 0x60, 0x0d, 0x3a, 0x03, 0x58,
	0xb0, 0xa2, 0x20, 0x0b, 0xf9, 0x86, 0xa3, 0x8d, 0xb4, 0xb1, 0x81, 0x6f, 0xdd, 0xa0, 0x21, 0xe8,
	0x34, 0x77, 0xf4, 0x91, 0x36, 0x1e, 0x60, 0x9d, 0xe6, 0xde, 0xaf, 0x4e, 0xfe, 0x85, 0xd1, 0x4a,
	0x90, 0x06, 0x05, 0x60, 0xe4, 0x5c, 0x28, 0x9d, 0x15, 0x9e, 0xfa, 0xbb, 0x76, 0xfd, 0x5b, 0xab,
	0xb0, 0x24, 0xd1, 0x0b, 0x18, 0x6c, 0x1d, 0xa9, 0x67, 0xad, 0xd0, 0xf5, 0x3b, 0xcf, 0xfe, 0xc6,
	0xb3, 0x9f, 0x6c, 0x08, 0x7c, 0x03, 0x7b, 0x7f, 0x74, 0x80, 0x24, 0xe3, 0x2b, 0x4c, 0x78, 0x5b,
	0x08, 0xf4, 0x04, 0x8e, 0xa9, 0x20, 0xe5, 0xff, 0xad, 0x56, 0x28, 0xba, 0x07, 0x27, 0x22, 0xe3,
	0xab, 0x74, 0x1d, 0xc8, 0xc0, 0x7d, 0x79, 0x8c, 0x72, 0xe4, 0x82, 0x59, 0xd3, 0x9a, 0x14, 0xb4,
	0x22, 0x8e, 0xa1, 0x26, 0xdb, 0x33, 0x7a, 0x06, 0x7d, 0x2e, 0x32, 0xd1, 0x72, 0xe7, 0x78, 0xa4,
	0x8d, 0x87, 0xe1, 0xc3, 0xfd, 0x4d, 0xd2, 0x55, 0xac, 0x18, 0xbc, 0x66, 0xd1, 0x6b, 0xb0, 0xae,
	0x68, 0x45, 0xf9, 0x75, 0x2a, 0x03, 0x38, 0xbd, 0x83, 0x41, 0xa1, 0xc3, 0xe5, 0x05, 0x7a, 0x0e,
	0xe6, 0xe6, 0x57, 0x9d, 0xbe, 0x52, 0xde, 0xdf, 0x53, 0xbe, 0x5f, 0x03, 0x78, 0x8b, 0x7a, 0x3e,
	0xdc, 0xfd, 0x48, 0x84, 0x34, 0xc3, 0x31, 0xf9, 0xde, 0x12, 0x2e, 0xd0, 0x03, 0x18, 0x54, 0x6d,
	0x99, 0xca, 0x98, 0x5c, 0x35, 0xd5, 0xc3, 0x66, 0xd5, 0x96, 0x8a, 0xf1, 0x2e, 0xc0, 0xbe, 0xe1,
	0x79, 0xcd, 0x2a, 0x4e, 0xd0, 0x4b, 0x30, 0x8b, 0xae, 0x33, 0xc9, 0x1b, 0x87, 0x9b, 0xdd, 0xe2,
	0x8f, 0x5f, 0x75, 0xdf, 0xd3, 0x15, 0x81, 0x2c, 0x38, 0x89, 0xe7, 0x93, 0xc9, 0x34, 0x8e, 0xed,
	0x23, 0x79, 0x48, 0xa2, 0x8b, 0xe9, 0xe7, 0x79, 0x62, 0x6b, 0x08, 0xc1, 0x70, 0x32, 0x8b, 0xa6,
	0x9f, 0x92, 0xf4, 0xc3, 0xdb, 0x68, 0x36, 0xc7, 0x53, 0x5b, 0x0f, 0xbf, 0x41, 0x4f, 0xf9, 0x40,
	0x31, 0x98, 0x1b, 0x4f, 0xe8, 0xd1, 0xfe, 0xe6, 0x9d, 0x7c, 0xae, 0xf7, 0x2f, 0xa4, 0x8b, 0xe4,
	0x1d, 0xbd, 0x3b, 0xff, 0x7a, 0xba, 0x64, 0x92, 0xf4, 0xd7, 0x64, 0x20, 0xc9, 0xa0, 0x5e, 0x2d,
	0x03, 0xf1, 0xbb, 0x26, 0xfc, 0xb2, 0xaf, 0x6a, 0x7d, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x77,
	0xd3, 0x43, 0x1e, 0x7d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TasksClient is the client API for Tasks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TasksClient interface {
	GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error)
}

type tasksClient struct {
	cc *grpc.ClientConn
}

func NewTasksClient(cc *grpc.ClientConn) TasksClient {
	return &tasksClient{cc}
}

func (c *tasksClient) GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error) {
	out := new(GetTasksResponse)
	err := c.cc.Invoke(ctx, "/od2_network.hive.Tasks/GetTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasksServer is the server API for Tasks service.
type TasksServer interface {
	GetTasks(context.Context, *GetTasksRequest) (*GetTasksResponse, error)
}

// UnimplementedTasksServer can be embedded to have forward compatible implementations.
type UnimplementedTasksServer struct {
}

func (*UnimplementedTasksServer) GetTasks(ctx context.Context, req *GetTasksRequest) (*GetTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}

func RegisterTasksServer(s *grpc.Server, srv TasksServer) {
	s.RegisterService(&_Tasks_serviceDesc, srv)
}

func _Tasks_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/od2_network.hive.Tasks/GetTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).GetTasks(ctx, req.(*GetTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tasks_serviceDesc = grpc.ServiceDesc{
	ServiceName: "od2_network.hive.Tasks",
	HandlerType: (*TasksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTasks",
			Handler:    _Tasks_GetTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models.proto",
}
