@startuml
title njobs architecture

component Kafka as Kafka_K1 {
  card "Tasks Topic" as Kafka_K1_Tasks {
    queue "Part 1" as KafkaTasks_P1
    queue "Part 2" as KafkaTasks_P2
  }
  card "Results Topic" as Kafka_K1_Results {
  }
}

component "Redis 1" as Redis_I1 {
  database NAssign as Redis_I1_NAssign
  queue Results as Redis_R1_Results
  queue Worker_1 as Redis_R1_Worker_1
  queue Worker_2 as Redis_R1_Worker_2
}

component "Assigner 1" as Assigner_A1

KafkaTasks_P1 ---> Assigner_A1: Tasks
Assigner_A1 ---> Redis_I1_NAssign: Tasks
Redis_I1_NAssign ---> Redis_R1_Worker_1
Redis_I1_NAssign ---> Redis_R1_Worker_2
Redis_R1_Results <-- Redis_I1_NAssign

Kafka_K1_Results <-- Redis_R1_Results

cloud Workers {
    component Worker_1 {
      agent W1_P1
      agent W1_P2
    }
    component Worker_2 {
      agent W2_P1
      agent W2_P2
      agent W2_P3
    }
    component Worker_3 {
      agent W3_P1
    }
}

Redis_R1_Worker_1 --> W1_P1
Redis_R1_Worker_1 --> W1_P2

Redis_R1_Worker_2 --> W2_P1
Redis_R1_Worker_2 --> W2_P2

component "Redis 2" as Redis_I2 {
  database NAssign as Redis_I2_NAssign
  queue Results as Redis_R2_Results
  queue Worker_2 as Redis_R2_Worker_2
  queue Worker_3 as Redis_R2_Worker_3
}

component "Assigner 2" as Assigner_A2

KafkaTasks_P2 ---> Assigner_A2: Tasks
Assigner_A2 ---> Redis_I2_NAssign: Tasks
Redis_I2_NAssign ---> Redis_R2_Worker_2
Redis_I2_NAssign ---> Redis_R2_Worker_3
Redis_R2_Results <-- Redis_I2_NAssign

Kafka_K1_Results <-- Redis_R2_Results

Redis_R2_Worker_2 --> W2_P3
Redis_R2_Worker_3 --> W3_P1

KafkaTasks_P1 -[hidden]-> Kafka_K1_Results
KafkaTasks_P2 -[hidden]-> Kafka_K1_Results

Redis_R1_Worker_2 <-[hidden] Redis_R1_Worker_1
@enduml
