on: [push]
name: Build
jobs:
  buildx:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '10'
    - name: Setup up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
